// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysRoleOffice is the golang structure of table sys_role_office for DAO operations like Where/Data.
type SysRoleOffice struct {
	g.Meta     `orm:"table:sys_role_office, do:true"`
	RoleId     interface{} // 角色编号
	OfficeId   interface{} // 机构编号
	Id         interface{} //
	CreateBy   interface{} //
	CreateDate *gtime.Time //
	UpdateBy   interface{} //
	UpdateDate *gtime.Time //
	DelFlag    interface{} //
}
