// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta     `orm:"table:sys_user, do:true"`
	Id         interface{} // 主键ID
	Username   interface{} // 用户名
	Password   interface{} // 密码
	JobNumber  interface{} // 工号
	Email      interface{} // 邮箱
	Phone      interface{} // 电话
	Mobile     interface{} // 手机
	OfficeId   interface{} // 部门ID
	CompanyId  interface{} // 公司ID
	UserType   interface{} // 用户类型(0.普通 1.超管)
	LoginIp    interface{} // 最后登陆IP
	LoginDate  *gtime.Time // 登陆时间
	CreateBy   interface{} // 创建者
	CreateDate *gtime.Time // 创建时间
	UpdateBy   interface{} // 更新者
	UpdateDate *gtime.Time // 更新时间
	Remark     interface{} // 备注
	Status     interface{} // 状态,0:删除,1:有效
}
