// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysDict is the golang structure of table sys_dict for DAO operations like Where/Data.
type SysDict struct {
	g.Meta     `orm:"table:sys_dict, do:true"`
	Id         interface{} // 编号
	Label      interface{} // 标签名
	Value      interface{} // 数据值
	Type       interface{} // 类型
	Desc       interface{} // 描述
	Sort       interface{} // 排序(升序)
	CreateBy   interface{} // 创建者
	CreateDate *gtime.Time // 创建时间
	UpdateBy   interface{} // 更新者
	UpdateDate *gtime.Time // 更新时间
	Remarks    interface{} // 备注信息
	Status     interface{} // 状态,0:删除,1:有效
}
