// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysResourceDao is the data access object for table sys_resource.
type SysResourceDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns SysResourceColumns // columns contains all the column names of Table for convenient usage.
}

// SysResourceColumns defines and stores column names for table sys_resource.
type SysResourceColumns struct {
	Id            string //
	Name          string // 资源名称
	Common        string // 是否是公共资源(0.不是 1.是)
	Icon          string // 图标
	Sort          string // 排序号
	ParentId      string // 父级id
	Type          string // 类型(0.菜单 1.按钮)
	Url           string // 链接
	Description   string // 描述
	Status        string // 状态(0.正常 1.禁用)
	ParentIds     string // 父级集合
	CreateDate    string //
	UpdateDate    string //
	CreateBy      string //
	UpdateBy      string //
	DelFlag       string //
	PermissionStr string //
}

//  sysResourceColumns holds the columns for table sys_resource.
var sysResourceColumns = SysResourceColumns{
	Id:            "id",
	Name:          "name",
	Common:        "common",
	Icon:          "icon",
	Sort:          "sort",
	ParentId:      "parent_id",
	Type:          "type",
	Url:           "url",
	Description:   "description",
	Status:        "status",
	ParentIds:     "parent_ids",
	CreateDate:    "create_date",
	UpdateDate:    "update_date",
	CreateBy:      "create_by",
	UpdateBy:      "update_by",
	DelFlag:       "del_flag",
	PermissionStr: "permission_str",
}

// NewSysResourceDao creates and returns a new DAO object for table data access.
func NewSysResourceDao() *SysResourceDao {
	return &SysResourceDao{
		group:   "default",
		table:   "sys_resource",
		columns: sysResourceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysResourceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysResourceDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysResourceDao) Columns() SysResourceColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysResourceDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysResourceDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysResourceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
