// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SysDictDao is the data access object for table sys_dict.
type SysDictDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns SysDictColumns // columns contains all the column names of Table for convenient usage.
}

// SysDictColumns defines and stores column names for table sys_dict.
type SysDictColumns struct {
	Id         string // 编号
	Label      string // 标签名
	Value      string // 数据值
	Type       string // 类型
	Desc       string // 描述
	Sort       string // 排序(升序)
	CreateBy   string // 创建者
	CreateDate string // 创建时间
	UpdateBy   string // 更新者
	UpdateDate string // 更新时间
	Remarks    string // 备注信息
	Status     string // 状态,0:删除,1:有效
}

//  sysDictColumns holds the columns for table sys_dict.
var sysDictColumns = SysDictColumns{
	Id:         "id",
	Label:      "label",
	Value:      "value",
	Type:       "type",
	Desc:       "desc",
	Sort:       "sort",
	CreateBy:   "create_by",
	CreateDate: "create_date",
	UpdateBy:   "update_by",
	UpdateDate: "update_date",
	Remarks:    "remarks",
	Status:     "status",
}

// NewSysDictDao creates and returns a new DAO object for table data access.
func NewSysDictDao() *SysDictDao {
	return &SysDictDao{
		group:   "default",
		table:   "sys_dict",
		columns: sysDictColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SysDictDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SysDictDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SysDictDao) Columns() SysDictColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SysDictDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SysDictDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SysDictDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
