# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:root:rootroot@tcp(127.0.0.1:3306)/FastGo"
        tables: "sys_area,sys_dict,sys_log,sys_office,sys_resource,sys_role,sys_role_office,sys_resource,sys_task,sys_user,sys_user_role"
        # 表前缀
        removePrefix: ""
        descriptionTag: true
        noModelComment: true