// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysTask interface {
	Creat(ctx context.Context, req *api.SysTaskCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysTaskUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysTask, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysTask, err error)
}

var localSysTask ISysTask

func SysTask() ISysTask {
	if localSysTask == nil {
		panic("implement not found for interface ISysTask, forgot register?")
	}
	return localSysTask
}

func RegisterSysTask(i ISysTask) {
	localSysTask = i
}
