// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysOffice interface {
	Creat(ctx context.Context, req *api.SysOfficeCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysOfficeUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysOffice, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysOffice, err error)
}

var localSysOffice ISysOffice

func SysOffice() ISysOffice {
	if localSysOffice == nil {
		panic("implement not found for interface ISysOffice, forgot register?")
	}
	return localSysOffice
}

func RegisterSysOffice(i ISysOffice) {
	localSysOffice = i
}
