// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysDict interface {
	Creat(ctx context.Context, req *api.SysDictCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysDictUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysDict, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysDict, err error)
}

var localSysDict ISysDict

func SysDict() ISysDict {
	if localSysDict == nil {
		panic("implement not found for interface ISysDict, forgot register?")
	}
	return localSysDict
}

func RegisterSysDict(i ISysDict) {
	localSysDict = i
}
