// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysArea interface {
	Creat(ctx context.Context, req *api.SysAreaCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysAreaUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysArea, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysArea, err error)
}

var localSysArea ISysArea

func SysArea() ISysArea {
	if localSysArea == nil {
		panic("implement not found for interface ISysArea, forgot register?")
	}
	return localSysArea
}

func RegisterSysArea(i ISysArea) {
	localSysArea = i
}
