// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysResource interface {
	Creat(ctx context.Context, req *api.SysResourceCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysResourceUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysResource, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysResource, err error)
}

var localSysResource ISysResource

func SysResource() ISysResource {
	if localSysResource == nil {
		panic("implement not found for interface ISysResource, forgot register?")
	}
	return localSysResource
}

func RegisterSysResource(i ISysResource) {
	localSysResource = i
}
