// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"

	"github.com/hong0220/FastGo/internal/api"
	"github.com/hong0220/FastGo/internal/model/entity"
	"github.com/hong0220/FastGo/pkg/common/base"
)

type ISysRoleOffice interface {
	Creat(ctx context.Context, req *api.SysRoleOfficeCreatReq) (err error)
	Delete(ctx context.Context, id int) (err error)
	DeleteByIds(ctx context.Context, ids []int) (err error)
	Update(ctx context.Context, req *api.SysRoleOfficeUpdateReq) (err error)
	GetId(ctx context.Context, id int) (res *entity.SysRoleOffice, err error)
	GetList(ctx context.Context, page *base.Page) (res []*entity.SysRoleOffice, err error)
}

var localSysRoleOffice ISysRoleOffice

func SysRoleOffice() ISysRoleOffice {
	if localSysRoleOffice == nil {
		panic("implement not found for interface ISysRoleOffice, forgot register?")
	}
	return localSysRoleOffice
}

func RegisterSysRoleOffice(i ISysRoleOffice) {
	localSysRoleOffice = i
}
