// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hong0220/FastGo/internal/dao/internal"
)

// internalSysTaskDao is internal type for wrapping internal DAO implements.
type internalSysTaskDao = *internal.SysTaskDao

// sysTaskDao is the data access object for table sys_task.
// You can define custom methods on it to extend its functionality as you wish.
type sysTaskDao struct {
	internalSysTaskDao
}

var (
	// SysTask is globally public accessible object for table sys_task operations.
	SysTask = sysTaskDao{
		internal.NewSysTaskDao(),
	}
)

// Fill with you ideas below.
