// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hong0220/FastGo/internal/dao/internal"
)

// internalSysResourceDao is internal type for wrapping internal DAO implements.
type internalSysResourceDao = *internal.SysResourceDao

// sysResourceDao is the data access object for table sys_resource.
// You can define custom methods on it to extend its functionality as you wish.
type sysResourceDao struct {
	internalSysResourceDao
}

var (
	// SysResource is globally public accessible object for table sys_resource operations.
	SysResource = sysResourceDao{
		internal.NewSysResourceDao(),
	}
)

// Fill with you ideas below.
