// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hong0220/FastGo/internal/dao/internal"
)

// internalSysRoleOfficeDao is internal type for wrapping internal DAO implements.
type internalSysRoleOfficeDao = *internal.SysRoleOfficeDao

// sysRoleOfficeDao is the data access object for table sys_role_office.
// You can define custom methods on it to extend its functionality as you wish.
type sysRoleOfficeDao struct {
	internalSysRoleOfficeDao
}

var (
	// SysRoleOffice is globally public accessible object for table sys_role_office operations.
	SysRoleOffice = sysRoleOfficeDao{
		internal.NewSysRoleOfficeDao(),
	}
)

// Fill with you ideas below.
