// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/hong0220/FastGo/internal/dao/internal"
)

// internalSysOfficeDao is internal type for wrapping internal DAO implements.
type internalSysOfficeDao = *internal.SysOfficeDao

// sysOfficeDao is the data access object for table sys_office.
// You can define custom methods on it to extend its functionality as you wish.
type sysOfficeDao struct {
	internalSysOfficeDao
}

var (
	// SysOffice is globally public accessible object for table sys_office operations.
	SysOffice = sysOfficeDao{
		internal.NewSysOfficeDao(),
	}
)

// Fill with you ideas below.
