// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysArea is the golang structure for table sys_area.
type SysArea struct {
	Id         int64       `json:"id"         description:"编号"`
	ParentId   int64       `json:"parentId"   description:"父级编号"`
	ParentIds  string      `json:"parentIds"  description:"所有父级编号"`
	Code       string      `json:"code"       description:"区域编码"`
	Name       string      `json:"name"       description:"区域名称"`
	Type       string      `json:"type"       description:"区域类型"`
	CreateBy   string      `json:"createBy"   description:"创建者"`
	CreateDate *gtime.Time `json:"createDate" description:"创建时间"`
	UpdateBy   string      `json:"updateBy"   description:"更新者"`
	UpdateDate *gtime.Time `json:"updateDate" description:"更新时间"`
	Remarks    string      `json:"remarks"    description:"备注信息"`
	DelFlag    string      `json:"delFlag"    description:"删除标记(0活null 正常 1,删除)"`
	Icon       string      `json:"icon"       description:""`
}
