// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUserRole is the golang structure for table sys_user_role.
type SysUserRole struct {
	Id         int64       `json:"id"         description:"主键ID"`
	RoleId     int64       `json:"roleId"     description:"角色ID"`
	UserId     int64       `json:"userId"     description:"用户ID"`
	CreateBy   string      `json:"createBy"   description:"创建者"`
	CreateDate *gtime.Time `json:"createDate" description:"创建时间"`
	UpdateBy   string      `json:"updateBy"   description:"更新者"`
	UpdateDate *gtime.Time `json:"updateDate" description:"更新时间"`
	Status     int         `json:"status"     description:"状态,0:删除,1:有效"`
}
