// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	Id         int64       `json:"id"         description:"主键ID"`
	Username   string      `json:"username"   description:"用户名"`
	Password   string      `json:"password"   description:"密码"`
	JobNumber  string      `json:"jobNumber"  description:"工号"`
	Email      string      `json:"email"      description:"邮箱"`
	Phone      string      `json:"phone"      description:"电话"`
	Mobile     string      `json:"mobile"     description:"手机"`
	OfficeId   int64       `json:"officeId"   description:"部门ID"`
	CompanyId  int64       `json:"companyId"  description:"公司ID"`
	UserType   string      `json:"userType"   description:"用户类型(0.普通 1.超管)"`
	LoginIp    string      `json:"loginIp"    description:"最后登陆IP"`
	LoginDate  *gtime.Time `json:"loginDate"  description:"登陆时间"`
	CreateBy   string      `json:"createBy"   description:"创建者"`
	CreateDate *gtime.Time `json:"createDate" description:"创建时间"`
	UpdateBy   string      `json:"updateBy"   description:"更新者"`
	UpdateDate *gtime.Time `json:"updateDate" description:"更新时间"`
	Remark     string      `json:"remark"     description:"备注"`
	Status     int         `json:"status"     description:"状态,0:删除,1:有效"`
}
