// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// User is the golang structure for table user.
type User struct {
	Id       uint64 `json:"id"       description:""`
	UserName string `json:"userName" description:""`
}
